version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  docker-in-docker:
    driver: ${VOLUMES_DRIVER}

services:
  #####################   WorkSpace   ###################
  workspace:
    build:
      context: ./workspace
      args:
        - PHP_VERSION=${PHP_VERSION}
        - CHANGE_SOURCE=${CHANGE_SOURCE}
        - UBUNTU_SOURCE=${UBUNTU_SOURCE}
        - SHELL_OH_MY_ZSH=${SHELL_OH_MY_ZSH}
        - TIMEZONE=${WORKSPACE_TIMEZONE}
        - INSTALL_SSH2=${WORKSPACE_INSTALL_SSH2}
        - INSTALL_LDAP=${WORKSPACE_INSTALL_LDAP}
        - INSTALL_SMB=${WORKSPACE_INSTALL_SMB}
        - INSTALL_XDEBUG=${WORKSPACE_INSTALL_XDEBUG}
        - INSTALL_PCOV=${WORKSPACE_INSTALL_PCOV}
        - INSTALL_MONGODB=${WORKSPACE_INSTALL_MONGODB}
        - INSTALL_AMQP=${WORKSPACE_INSTALL_AMQP}
        - INSTALL_CASSANDRA=${WORKSPACE_INSTALL_CASSANDRA}
        - INSTALL_GEARMAN=${WORKSPACE_INSTALL_GEARMAN}
        - INSTALL_SWOOLE=${WORKSPACE_INSTALL_SWOOLE}
        - INSTALL_TAINT=${WORKSPACE_INSTALL_TAINT}
        - INSTALL_INOTIFY=${WORKSPACE_INSTALL_INOTIFY}
        - INSTALL_AST=${WORKSPACE_INSTALL_AST}
        - AST_VERSION=${WORKSPACE_AST_VERSION}
        - INSTALL_PHALCON=${WORKSPACE_INSTALL_PHALCON}
        - PHALCON_VERSION=${PHALCON_VERSION}
        - INSTALL_AEROSPIKE=${WORKSPACE_INSTALL_AEROSPIKE}
        - INSTALL_IONCUBE=${WORKSPACE_INSTALL_IONCUBE}
        - COMPOSER_GLOBAL_INSTALL=${WORKSPACE_COMPOSER_GLOBAL_INSTALL}
        - COMPOSER_AUTH=${WORKSPACE_COMPOSER_AUTH}
        - COMPOSER_REPO_PACKAGIST=${WORKSPACE_COMPOSER_REPO_PACKAGIST}
        - INSTALL_LARAVEL_ENVOY=${WORKSPACE_INSTALL_LARAVEL_ENVOY}
        - INSTALL_LARAVEL_INSTALLER=${WORKSPACE_INSTALL_LARAVEL_INSTALLER}
        - INSTALL_PRESTISSIMO=${WORKSPACE_INSTALL_PRESTISSIMO}
        - INSTALL_PING=${WORKSPACE_INSTALL_PING}
        - INSTALL_SSHPASS=${WORKSPACE_INSTALL_SSHPASS}
        - INSTALL_GNU_PARALLEL=${WORKSPACE_INSTALL_GNU_PARALLEL}
        - INSTALL_DEPLOYER=${WORKSPACE_INSTALL_DEPLOYER}
        - INSTALL_MC=${WORKSPACE_INSTALL_MC}
        - INSTALL_SYMFONY=${WORKSPACE_INSTALL_SYMFONY}
        - INSTALL_PYTHON=${WORKSPACE_INSTALL_PYTHON}
        - INSTALL_DRUPAL_CONSOLE=${WORKSPACE_INSTALL_DRUPAL_CONSOLE}
        - INSTALL_SUPERVISOR=${WORKSPACE_INSTALL_SUPERVISOR}
        - INSTALL_DRUSH=${WORKSPACE_INSTALL_DRUSH}
        - DRUSH_VERSION=${WORKSPACE_DRUSH_VERSION}
        - INSTALL_LINUXBREW=${WORKSPACE_INSTALL_LINUXBREW}
        - CHROME_DRIVER_VERSION=${WORKSPACE_CHROME_DRIVER_VERSION}
        - INSTALL_DUSK_DEPS=${WORKSPACE_INSTALL_DUSK_DEPS}
        - INSTALL_SUBVERSION=${WORKSPACE_INSTALL_SUBVERSION}
        - INSTALL_BLACKFIRE=${INSTALL_BLACKFIRE}
        - BLACKFIRE_CLIENT_ID=${BLACKFIRE_CLIENT_ID}
        - BLACKFIRE_CLIENT_TOKEN=${BLACKFIRE_CLIENT_TOKEN}
        - INSTALL_FSWATCH=${WORKSPACE_INSTALL_FSWATCH}
        - INSTALL_GIT_PROMPT=${WORKSPACE_INSTALL_GIT_PROMPT}
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${SUPERVISORD_PATH_HOST}:/etc/supervisord.d
      - ${SSH_KEY_PATH_HOST}:/root/.ssh
      - docker-in-docker:/certs/client
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    ports:
      - "${WORKSPACE_SSH_PORT}:22"
    tty: true
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      - DOCKER_HOST=tcp://docker-in-docker:2376
      - DOCKER_TLS_VERIFY=1
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_CERT_PATH=/certs/client
    networks:
      - frontend
      - backend
    links:
      - docker-in-docker
  #####################   PHP-FPM     ###################
  php-fpm:
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
        - INSTALL_APCU=${PHP_FPM_INSTALL_APCU}
        - INSTALL_BCMATH=${PHP_FPM_INSTALL_BCMATH}
        - INSTALL_BZ2=${PHP_FPM_INSTALL_BZ2}
        - INSTALL_CALENDAR=${PHP_FPM_INSTALL_CALENDAR}
        - INSTALL_EXIF=${PHP_FPM_INSTALL_EXIF}
        - INSTALL_GD=${PHP_FPM_INSTALL_GD}
        - INSTALL_GEARMAN=${PHP_FPM_INSTALL_GEARMAN}
        - INSTALL_GETTEXT=${PHP_FPM_INSTALL_GETTEXT}
        - INSTALL_GRPC=${PHP_FPM_INSTALL_GRPC}
        - INSTALL_IGBINARY=${PHP_FPM_INSTALL_IGBINARY}
        - INSTALL_IMAP=${PHP_FPM_INSTALL_IMAP}
        - INSTALL_MEMCACHE=${PHP_FPM_INSTALL_MEMCACHE}
        - INSTALL_MEMCACHED=${PHP_FPM_INSTALL_MEMCACHED}
        - INSTALL_MONGODB=${PHP_FPM_INSTALL_MONGODB}
        - INSTALL_MSGPACK=${PHP_FPM_INSTALL_MSGPACK}
        - INSTALL_MYSQLI=${PHP_FPM_INSTALL_MYSQLI}
        - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
        - INSTALL_PCNTL=${PHP_FPM_INSTALL_PCNTL}
        - INSTALL_PCOV=${PHP_FPM_INSTALL_PCOV}
        - INSTALL_PDO_MYSQL=${PHP_FPM_INSTALL_PDO_MYSQL}
        - INSTALL_PROTOBUF=${PHP_FPM_INSTALL_PROTOBUF}
        - INSTALL_REDIS=${PHP_FPM_INSTALL_REDIS}
        - INSTALL_SOAP=${PHP_FPM_INSTALL_SOAP}
        - INSTALL_SOCKETS=${PHP_FPM_INSTALL_SOCKETS}
        - INSTALL_SSH2=${PHP_FPM_INSTALL_SSH2}
        - INSTALL_SWOOLE=${PHP_FPM_INSTALL_SWOOLE}
        - INSTALL_WDDX=${PHP_FPM_INSTALL_WDDX}
        - INSTALL_TAINT=${PHP_FPM_INSTALL_TAINT}
        - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
        - INSTALL_XHPROF=${PHP_FPM_INSTALL_XHPROF}
        - INSTALL_XSL=${PHP_FPM_INSTALL_XSL}
        - INSTALL_YAML=${PHP_FPM_INSTALL_YAML}
        - INSTALL_ZIP=${PHP_FPM_INSTALL_ZIP}
        - INSTALL_FAKETIME=${PHP_FPM_INSTALL_FAKETIME}
        - PUID=${PHP_FPM_PUID}
        - PGID=${PHP_FPM_PGID}
        - LOCALE=${PHP_FPM_DEFAULT_LOCALE}
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ./php-fpm/conf/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
      - ${PHP_FPM_HOST_LOG_PATH}:/var/log/php-fpm
      - docker-in-docker:/certs/client
    expose:
      - "9000"
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      - DOCKER_HOST=tcp://docker-in-docker:2376
      - DOCKER_TLS_VERIFY=1
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_CERT_PATH=/certs/client
      - FAKETIME=${PHP_FPM_FAKETIME}
    networks:
      - backend
    links:
      - docker-in-docker
  #####################   NGINX       ###################
  nginx:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      - ${NGINX_CONF_PATH}:/etc/nginx/nginx.conf
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
    networks:
      - backend
  ### Docker-in-Docker ###
  docker-in-docker:
    image: docker:19.03-dind
    environment:
      DOCKER_TLS_SAN: DNS:docker-in-docker
    privileged: true
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - docker-in-docker:/certs/client
    expose:
      - 2375
    networks:
      - backend